# dein.toml
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
# exec shell, obsolete.
repo = 'Shougo/vimshell'

[[plugins]]
# fzf impliments.
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
# fzf for vim.
repo = 'junegunn/fzf.vim'
depend = 'fzf'

[[plugins]]
# scheme.
repo = 'tomasr/molokai'
merged = '0'

[[plugins]]
# nerdtree
repo = 'scrooloose/nerdtree'

[[plugins]]
# nerdtree plugins
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = 'nerdtree'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'vim-scripts/vcscommand.vim'

[[plugins]]
repo = 'vim-syntastic/syntastic'

#[[plugins]]
#repo = 'roxma/nvim-yarp'
#on_if = '!has("nvim")'
#
#[[plugins]]
#repo = 'roxma/vim-hug-neovim-rpc'
#on_if = '!has("nvim")'
#
#[[plugins]]
#repo = 'Shougo/deoplete.nvim'
#depends = ['context_filetype.vim', 'nvim-yarp', 'vim-hug-neovim-rpc']
#hook_add = '''
#    let g:deoplete#enable_at_startup = 1
#'''
### let g:deoplete#enable_at_startup = 1
### let g:deoplete#enable_smart_case = 1
