# dein lazy file
[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
#obsolete
repo = 'Shougo/unite.vim'

[[plugins]]
# unite mru
repo = 'Shougo/neomru.vim'
depends = 'Shougo/unite.vim'

[[plugins]]
#exec snippets
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'

[[plugins]]
# some snippets
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
# for markdown preview
repo = 'kannokanno/previm'
on_cmd = 'PrevimOpen'
depends = 'open-browser.vim'

[[plugins]]
# open browser
repo = 'tyru/open-browser.vim'

[[plugins]]
# for markdown
repo = 'plasticboy/vim-markdown'

[[plugins]]
# golang
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
# JSON
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
# rust Utility
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
let g:rustfmt_autosave = 1
let g:rustfmt_command = '$HOME/.cargo/bin/rustfmt'
'''
[[plugins]]
# rust completion
repo = 'sebastianmarkow/deoplete-rust'
on_ft = 'rust'
hook_source = '''
let g:deoplete#sources#rust#racer_binary='$HOME/.cargo/bin/racer'
let g:deoplete#sources#rust#rust_source_path='$RUST_SRC_PATH'
let g:deoplete#sources#rust#show_duplicates=1
let g:deoplete#sources#rust#disable_keymap=1
let g:deoplete#sources#rust#documentation_max_height=20
'''

[[plugins]]
# python jedi
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_source = '''
let g:jedi#rename_command = "<leader>R"
let g:jedi#popup_on_dot = 1
autocmd FileType python let b:did_ftplugin = 1
'''

[[plugins]]
repo = 'andviro/flake8-vim'
on_ft = 'python'
hook_source = '''
let g:PyFlakeOnWrite = 1
let g:PyFlakeCheckers = 'pep8,frosted'
'''

#[[plugins]]
## neco
#repo = 'Shougo/neocomplete.vim'
#on_i = 1

[[plugins]]
repo = 'roxma/nvim-yarp'
on_if = '!has("nvim")'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = ['context_filetype.vim', 'nvim-yarp', 'vim-hug-neovim-rpc']
on_i = 1
hook_add = '''
    let g:deoplete#enable_at_startup = 1
'''
# let g:deoplete#enable_at_startup = 1
# let g:deoplete#enable_smart_case = 1

